### ISSUE TITLE
Why use harmonic mean?

### ISSUE THREAD

**Issue by hongliang-wei** [jmhessel/clipscore#18]
Thank you for your great work.
Why use harmonic mean?

**Comment by jmhessel** [comment]
Hi @tgyy1995 !

It's a good question, and thanks for your interest in our work! Thinking back, the qualitative motivation for using the harmonic mean instead of the arithmetic mean between image-text/reference-text was to implement something closer to "and" logic versus "or" logic (i.e., for a caption to be good, it must satisfy image-text _and_ reference-text).

To be honest, I didn't thoroughly explore many different types of means: harmonic "just worked" on the first try.

Jack
